on: push
jobs:
  random-secret:
    runs-on: ubuntu-latest
    steps:
      - id: sets-a-secret
        run: |
          the_secret=$((RANDOM))
          echo "::add-mask::$the_secret"
          echo "::set-output name=secret-number::$the_secret"
      - run: |
          echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"
    outputs:
      number: ${{ steps.sets-a-secret.outputs.secret-number }}"
  follower:
    runs-on: ubuntu-latest
    needs: random-secret
    steps:
      - run: |
          echo "the secret number is ${{ needs.random-secret.outputs.number }}"
